import { execSync } from "child_process";
import Anthropic from "@anthropic-ai/sdk";

const client = new Anthropic({
  apiKey: process.env.ANTHROPIC_API_KEY,
});

const BOT_HEADER = "## 🤖 AI Code Review — Claude";

const MAX_DIFF_LENGTH = 80_000;

const REVIEW_PROMPT = `
You are a senior software engineer reviewing a pull request.

Analyze the following diff and provide feedback on:

- potential bugs
- security issues
- performance problems
- maintainability

Ignore formatting and linting issues.

Write the review in Spanish.
Use markdown with clear sections.
`;

function run(cmd) {
  return execSync(cmd, { encoding: "utf-8" }).trim();
}

function getDiff() {
  const { BASE_SHA, HEAD_SHA } = process.env;

  run("git fetch origin");

  let diff = run(`git diff origin/${BASE_SHA}...${HEAD_SHA}`);

  if (!diff.trim()) return null;

  if (diff.length > MAX_DIFF_LENGTH) {
    diff = diff.substring(0, MAX_DIFF_LENGTH) + "\n\n[diff truncated]";
  }

  return diff;
}

async function callClaude(diff) {
  console.log("🔍 Analyzing diff with Claude...");

  const response = await client.messages.create({
    model: "claude-opus-4-6",
    max_tokens: 3000,
    messages: [
      {
        role: "user",
        content: REVIEW_PROMPT + "\n\nDiff:\n" + diff,
      },
    ],
  });

  return response?.content?.[0]?.text ?? "No review generated.";
}

async function getPRThreads() {
  const { AZURE_DEVOPS_TOKEN, ORGANIZATION, PROJECT, REPO_ID, PR_ID } =
    process.env;

  const url =
    `${ORGANIZATION}/${encodeURIComponent(PROJECT)}` +
    `/_apis/git/repositories/${REPO_ID}/pullRequests/${PR_ID}/threads?api-version=7.1`;

  const response = await fetch(url, {
    headers: { Authorization: `Bearer ${AZURE_DEVOPS_TOKEN}` },
  });

  if (!response.ok) return [];

  const data = await response.json();
  return data.value || [];
}

async function resolveThread(threadId) {
  const { AZURE_DEVOPS_TOKEN, ORGANIZATION, PROJECT, REPO_ID, PR_ID } =
    process.env;

  const url =
    `${ORGANIZATION}/${encodeURIComponent(PROJECT)}` +
    `/_apis/git/repositories/${REPO_ID}/pullRequests/${PR_ID}/threads/${threadId}?api-version=7.1`;

  await fetch(url, {
    method: "PATCH",
    headers: {
      Authorization: `Bearer ${AZURE_DEVOPS_TOKEN}`,
      "Content-Type": "application/json",
    },
    body: JSON.stringify({ status: 2 }),
  });
}

async function resolvePreviousBotThreads() {
  const threads = await getPRThreads();

  const botThreads = threads.filter(
    (t) => t.comments?.[0]?.content?.startsWith(BOT_HEADER) && t.status !== 2,
  );

  await Promise.all(botThreads.map((t) => resolveThread(t.id)));

  console.log(`🧹 Resolved ${botThreads.length} previous bot reviews`);
}

async function postPRComment(review) {
  const { AZURE_DEVOPS_TOKEN, ORGANIZATION, PROJECT, REPO_ID, PR_ID } =
    process.env;

  const url =
    `${ORGANIZATION}/${encodeURIComponent(PROJECT)}` +
    `/_apis/git/repositories/${REPO_ID}/pullRequests/${PR_ID}/threads?api-version=7.1`;

  const body = `
  ${BOT_HEADER}

  ${review}

  ---
  *Generated by Claude AI reviewer*
  `;

  const response = await fetch(url, {
    method: "POST",
    headers: {
      Authorization: `Bearer ${AZURE_DEVOPS_TOKEN}`,
      "Content-Type": "application/json",
    },
    body: JSON.stringify({
      comments: [{ parentCommentId: 0, content: body, commentType: 1 }],
      status: 1,
    }),
  });

  if (!response.ok) {
    const error = await response.text();
    console.error("Error posting PR comment:", error);
    process.exit(1);
  }

  console.log(`✅ Review posted on PR #${PR_ID}`);
}

async function main() {
  const diff = getDiff();

  if (!diff) {
    console.log("No changes detected.");
    return;
  }

  await resolvePreviousBotThreads();

  const review = await callClaude(diff);

  await postPRComment(review);
}

main().catch((err) => {
  console.error("Unexpected error:", err);
  process.exit(1);
});
